# Sets the default token balance of a first-time joiner.
default-balance: 25

# When MySQL is enabled, all datas will be stored in the selected database.
# Else, all datas will be stored in the local flatfile database. (data.yml)
mysql:
  enabled: false
  hostname: 127.0.0.1
  port: 3306
  username: root
  password: password
  database: yourdatabase

# If enabled, when the command /token shop is executed, it will open the configured shop to player
# instead of displaying the usage.
# Also disables opening a shop by name, means typing '/token shop awesomeshop'
# will still open the default shop set below.
use-default:
  enabled: false
  shop: test

# Set a delay between clicking on shop items. Set to 0 for no delay.
# Prevents players clicking fast, improving server's performance.
click-delay: 0

# Edit messages displayed in-game here.
Messages:
  # Displayed when user is not authorized for certain action.
  # Possible placeholder(s):
  # %permission% - Gets the permission user is missing.
  no-permission: '&cNope! You are missing %permission% to do this.'

  # Displayed when user types an invalid amount for following actions: Add/Remove/Send/Set
  # Note: Also displayed when they do not have enough to send.
  # Possible placeholder(s):
  # %input% - Gets the input of what user typed for amount selection.
  invalid-amount: '&c''%input%'' is invalid! Please select a valid amount.'

  # Displayed when user attempts to execute actions to another user but user was not found.
  # Possible placeholder(s):
  # %input% - Gets the input of what user typed for target's username.
  invalid-player: '&cFailed to find a user named ''%input%''.'

  # Displayed when user types an invalid shop name.
  # Possible placeholder(s):
  # %input% - Gets the input of what user typed for shop name.
  invalid-shop: '&cThere was no shop found with the name ''%input%''.'

  # Displayed when user attempts to use a sub command from the following commands but sub command was invalid: /tm, /token
  # Possible placeholder(s):
  # %input% - Gets the input of what user typed for sub command.
  # %command% - Gets the main command of the sub command.
  invalid-sub-command: '&bTM &8» &7''&b%input%&7'' is not a valid sub command. Please type ''&b/%command%&7'' for help.'

  # Displayed when user does not have enough tokens for certain actions.
  # Possible placeholder(s):
  # %needed% - Gets the amount of tokens user is in need to perform the action.
  not-enough-tokens: '&cNot enough tokens! You need %needed% tokens more.'

  # Displayed when data is empty while trying to load the top 10 balances.
  # No placeholders available
  no-data: '&cNot enough data found to display the top token balances.'

  # Displayed when user is still on a click cooldown.
  # Possible placeholder(s):
  # %remaining% - Gets the cooldown remaining for the next purchase.
  click-spamming: '&cYou''re clicking too fast! Try with a little delay. (%remaining%)'

  # Displayed when user performs the command: /token
  # Possible placeholder(s):
  # %tokens% - Gets the command sender's token balance.
  token-help-page:
  - '&8&m*]----------[*&r &9T&boken&9M&banager &8&m*]----------[*&r'
  - '&7Your token balance: &b%tokens% tokens'
  - '&b/token balance &9<&busername&9> &8» &7Check people''s token balance.'
  - '&b/token send &9<&busername&9> <&bamount&9> &8» &7Send tokens to players.'
  - '&b/token shop &9<&bname&9> &8» &7Opens selected shop.'
  - '&b/token shops &8» &7Displays a list of loaded shops.'
  - '&b/token top &8» &7Displays the top token balances.'
  - '&8&m*]------------------------------------[*&r'

  # Displayed when user performs the command: /tm
  # No placeholders available
  tm-help-page:
  - '&8&m*]----------[*&r &9T&boken&9M&banager &8&m*]----------[*&r'
  - '&7Required permission: &ctokenmanager.admin'
  - '&b/tm add &9<&busername&9> <&bamount&9> &8» &7Add tokens to player.'
  - '&b/tm remove &9<&busername&9> <&bamount&9> &8» &7Remove tokens from player.'
  - '&b/tm set &9<&busername&9> <&bamount&9> &8» &7Set tokens of a player.'
  - '&b/tm open &9<&busername&9> &9<&bname&9> &8» &7Open a shop for player.'
  - '&b/tm reload &8» &7Reloads the plugin.'
  - '&8&m*]---------------------------------[*&r'

  # Displayed when user performs a certain sub command but the length of the arguments is smaller than minimum length of the sub command.
  # Possible placeholder(s):
  # %command% - Gets the main command of the sub command.
  # %usage% - Gets the usage of the sub command.
  sub-command-usage: '&bTM &8» &7Usage of this sub command is ''&b/%command% %usage%&7''.'

  # Displayed when user performs the sub command: /token top
  # Possible placeholder(s):
  # %users% - Gets the total loaded users' size.
  top-total-users: '&bTM &8» &7Total users: &b%users%'

  # Displayed when user performs the sub command: /token top
  # Possible placeholder(s):
  # %remaining% - Gets the time remaining util the next top 10 balances update.
  top-next-update: '&bTM &8» &7Next update: &b%remaining%'

  # Displayed when user performs the sub command: /token top
  # No placeholders available
  top-header: '&8&m*]------[*&r &7Top &b10 &7balances &8&m*]------[*&r'

  # Displayed when user performs the sub command: /token top
  # Possible placeholder(s):
  # %rank% - Gets the rank of the user.
  # %name% - Gets the name of the user.
  # %tokens% - Gets the token balance of the user.
  top-format: '&7%rank%. &b%name% &7with &b%tokens% token(s)'

  # Displayed when user performs the sub command: /token top
  # No placeholders available
  top-footer: '&8&m*]------------------------------[*&r'

  # Displayed when user performs the sub command: /token balance
  # Possible placeholder(s):
  # %tokens% - Gets the token balance of the user.
  balance: '&bTM &8» &7Your token balance is &b%tokens% token(s)&7.'

  # Displayed when user performs the sub command: /token balance [username]
  # Possible placeholder(s):
  # %tokens% - Gets the token balance of the selected user.
  balance-others: '&bTM &8» &7%player%''s token balance is &b%tokens% token(s)&7.'

  # Displayed when user performs the sub command: /token send [username] [amount]
  # Possible placeholder(s):
  # %amount% - Gets the amount sent.
  # %player% - Gets the selected user's name.
  on-send: '&bTM &8» &7Sent &b%amount% tokens &7to %player%.'

  # Displayed when user receive tokens.
  # Possible placeholder(s):
  # %amount% - Gets the amount received.
  on-receive: '&bTM &8» &b%amount% tokens &7has been added to your balance.'

 # Displayed when user spends/gets removed tokens.
  # Possible placeholder(s):
  # %amount% - Gets the amount removed.
  on-take: '&bTM &8» &b%amount% tokens &7has been removed from your balance.'

  # Displayed when user performs the sub command: /token add [username] [amount]
  # Possible placeholder(s):
  # %amount% - Gets the amount added.
  # %player% - Gets the selected user's name.
  on-add: '&bTM &8» &7Added &b%amount% tokens &7to %player%.'

  # Displayed when user performs the sub command: /token remove [username] [amount]
  # Possible placeholder(s):
  # %amount% - Gets the amount removed.
  # %player% - Gets the selected user's name.
  on-remove: '&bTM &8» &7Removed &b%amount% tokens &7from %player%.'

  # Displayed when user performs the sub command: /token set [username] [amount]
  # Possible placeholder(s):
  # %amount% - Gets the amount set.
  # %player% - Gets the selected user's name.
  on-set: '&bTM &8» &7Set %player%''s tokens to &b%amount% tokens&7.'

  # Displayed when user performs the sub command: /tm open [username] [shop]
  # Possible placeholder(s):
  # %name% - Gets the shop's name.
  # %player% - Gets the selected user's name.
  on-open: '&bTM &8» &7Opened shop &b%name% &7for %player%.'

  # Displayed when user performs the sub command: /token shops
  # Possible placeholder(s):
  # %shops% - Gets a list of shop names.
  shops: '&bTM &8» &7Shops: &b%shops%'